name: Run Ansible Playbook

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Run Ansible playbook
      run: ansible-playbook /opt/argo.yaml
      env:
        ANSIBLE_HOST_KEY_CHECKING: false
