name: Deploy with Ansible

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    #- name: Run Ansible playbook
    #  run: ansible-playbook -i ${{ secrets.HOST_IP }} -u ${{ secrets.SSH_USERNAME }} opt/argo.yaml
    #  env:
    #    SSH_PASSWORD: ${{ secrets.SSH_PRIVATE_KEY }}
    #    HOST_IP: ${{ secrets.HOST_IP }}
    #    SSH_USERNAME: ${{ secrets.SSH_USERNAME }}

    - name: Run ansible playbook
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_IP }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.REMOTE_PORT }}  # Optional: specify if using a non-standard SSH port
        script: |
          echo "Running a Linux command remotely"
          ansible-playbook opt/argo.yaml
          
